version: '3.1'

services:
  web:
    build:
      context: .
    container_name: web
    platform: linux/amd64
    depends_on:
      - db
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/var/www/html
      - ./web/nginx:/etc/nginx/conf.d
      - ./web/ssl:/etc/nginx/ssl

  php:
    build: 
      context: .
      dockerfile: PhpDockerfile
    container_name: php
    platform: linux/amd64
    volumes:
        - ./htdocs:/var/www/html
        - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  db:
    build:
      context: .
      dockerfile: DbDockerfile
    container_name: db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/conf:/etc/mysql/mysql.conf.d
      - ./db/backup:/backup
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
    ports:
      - 8081:80

  node:
    build: 
      context: .
      dockerfile: NodeDockerfile
    container_name: node
    volumes:
        - ./htdocs:/var/www/html
        - ./web/ssl:/etc/nginx/ssl
        - ./scripts:/scripts
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - 8001:8001
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./web/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  dbdata:
